server:
  servlet:
    context-path: /api/horse-harness-service

spring:
  datasource:
    url: jdbc:h2:mem:horseharness
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
  liquibase:
    enabled: true
    change-log: classpath:/liquibase/changelog-master.xml
    contexts: ${LIQUIBASE_CONTEXTS:default}
    database-change-log-table: databasechangelog
    database-change-log-lock-table: databasechangeloglock

logging:
  level:
    root: info