CREATE TABLE SECTIONAL_DATA
(
    SECTIONAL_DATA_ID          VARCHAR(50) NOT NULL PRIMARY KEY,
    HORSE_CODE                 VARCHAR(8)  NOT NULL,
    RACE_CODE                  VARCHAR(11) NOT NULL,
    HORSE_IMPORTED_COUNTRY     VARCHAR(33) NOT NULL,
    FINISHING_PLACE            INTEGER     NOT NULL,
    RUNNER_MARGIN_FOR_WINNER   INTEGER     NOT NULL,
    RUNNER_MARGIN_FOR_800_MARK INTEGER     NOT NULL,
    RUNNER_MARGIN_FOR_400_MARK INTEGER     NOT NULL,
    RUNNER_WIDTH_FOR_800_MARK  INTEGER     NOT NULL,
    RUNNER_WIDTH_FOR_400_MARK  INTEGER     NOT NULL,
    RACE_FINISH_TIME           VARCHAR(33)     NOT NULL,
    RACE_800_FINISH_TIME       VARCHAR(33)     NOT NULL,
    RACE_400_FINISH_TIME       VARCHAR(33)     NOT NULL,
    FILE_NAME       VARCHAR(255)     NOT NULL
);